language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
  - rust: nightly

notifications:
  slack:
    secure: mhiCB+CaFX2EnK3sluEJ1jprV1x5ns93EjoWP1bZa2Buk7/vR68WC8Wni5TZqmoMbl4sU1WQOD59fh5q6iSMqGFyAtB5ZwPbE3lhdFAWZkqkpZNGeb0tuYfqPDkjqnTjpHNJsOREtwzWvfQcFZ+ZqpSCX7FZqftw0BuNpFIs57598osJPq6AWQajBBpVJiaWFQBGQJj2DJ7yqK0YAVsEffZJViRCH7gW9WALiiXABb4Jqn7soKw5dC1oAw0N9mJj0dDmA+DrkhRuxCKFFGJBUeY4zRr6DEEjM7IqxmdK3xSd/pxuXj77ipb2/IgKFBxdT53UObW+/8Iuom1pJ7K/cNjffQp/pHKluila/ykUmVZ50oqbzYN+dgN+Ii3C8V25jRHJcZFWjZVpF0iHJuSEGbr9O8rpkEFu/+sb9VEIiNZ6oAHRIVMQGeR07dCUvchRNkSy1ybg8S+ffqGhcFq7ls7YzrPsnZrx1fBwM8PF7JPQPqDUTXNfYHgoRueABTegfmXftgN2PmH4kHvvw0sjzWzSe5QrK5fyb/NFrknoaabuMF3u9je66llNnVB79PprJfnW/781ZwWdit6rw8Kp2USRHQRyCGJwO8BELo/NDPo3WLK2OJvhvcguZInJg454topkR1n2fLSK3gj1mhjSJAzrL6l1OppfiH+GJ07M8+A=
